[2021-05-07 15:38:42,828] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: python_dag.helloworld 2020-05-02T18:58:00+00:00 [queued]>
[2021-05-07 15:38:43,327] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: python_dag.helloworld 2020-05-02T18:58:00+00:00 [queued]>
[2021-05-07 15:38:43,328] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:38:43,328] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-05-07 15:38:43,329] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:38:43,499] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): helloworld> on 2020-05-02T18:58:00+00:00
[2021-05-07 15:38:43,553] {standard_task_runner.py:52} INFO - Started process 11377 to run task
[2021-05-07 15:38:43,616] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_dag', 'helloworld', '2020-05-02T18:58:00+00:00', '--job-id', '53', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_python.py', '--cfg-path', '/tmp/tmp1sntvvpb', '--error-file', '/tmp/tmprpc1swrj']
[2021-05-07 15:38:43,636] {standard_task_runner.py:77} INFO - Job 53: Subtask helloworld
[2021-05-07 15:38:45,116] {logging_mixin.py:104} INFO - Running <TaskInstance: python_dag.helloworld 2020-05-02T18:58:00+00:00 [running]> on host jaarora-WX-1.corp.adobe.com
[2021-05-07 15:38:48,066] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jacrod2901@gmail.com
AIRFLOW_CTX_DAG_OWNER=jacrod2901
AIRFLOW_CTX_DAG_ID=python_dag
AIRFLOW_CTX_TASK_ID=helloworld
AIRFLOW_CTX_EXECUTION_DATE=2020-05-02T18:58:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-02T18:58:00+00:00
[2021-05-07 15:38:48,078] {python.py:118} INFO - Done. Returned value was: Printing hello world!
[2021-05-07 15:38:50,536] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=python_dag, task_id=helloworld, execution_date=20200502T185800, start_date=20210507T100842, end_date=20210507T100850
[2021-05-07 15:38:51,437] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-05-07 15:38:51,544] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 11377
[2021-05-07 15:38:51,978] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-07 15:38:52,267] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-07 15:38:52,319] {process_utils.py:66} INFO - Process psutil.Process(pid=11377, status='terminated', exitcode=0, started='15:38:43') (11377) terminated with exit code 0
