[2021-05-07 15:39:33,358] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: python_dag.helloworld 2020-05-02T19:50:00+00:00 [queued]>
[2021-05-07 15:39:33,704] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: python_dag.helloworld 2020-05-02T19:50:00+00:00 [queued]>
[2021-05-07 15:39:33,704] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:39:33,705] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-05-07 15:39:33,705] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:39:33,777] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): helloworld> on 2020-05-02T19:50:00+00:00
[2021-05-07 15:39:33,821] {standard_task_runner.py:52} INFO - Started process 12278 to run task
[2021-05-07 15:39:33,867] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_dag', 'helloworld', '2020-05-02T19:50:00+00:00', '--job-id', '79', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_python.py', '--cfg-path', '/tmp/tmpvvtn5666', '--error-file', '/tmp/tmpv86i_622']
[2021-05-07 15:39:33,888] {standard_task_runner.py:77} INFO - Job 79: Subtask helloworld
[2021-05-07 15:39:35,147] {logging_mixin.py:104} INFO - Running <TaskInstance: python_dag.helloworld 2020-05-02T19:50:00+00:00 [running]> on host jaarora-WX-1.corp.adobe.com
[2021-05-07 15:39:36,739] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jacrod2901@gmail.com
AIRFLOW_CTX_DAG_OWNER=jacrod2901
AIRFLOW_CTX_DAG_ID=python_dag
AIRFLOW_CTX_TASK_ID=helloworld
AIRFLOW_CTX_EXECUTION_DATE=2020-05-02T19:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-02T19:50:00+00:00
[2021-05-07 15:39:36,742] {python.py:118} INFO - Done. Returned value was: Printing hello world!
[2021-05-07 15:39:40,640] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=python_dag, task_id=helloworld, execution_date=20200502T195000, start_date=20210507T100933, end_date=20210507T100940
[2021-05-07 15:39:42,076] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-05-07 15:39:42,137] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 12278
[2021-05-07 15:39:42,172] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-07 15:39:42,283] {process_utils.py:66} INFO - Process psutil.Process(pid=12278, status='terminated', exitcode=1, started='15:39:33') (12278) terminated with exit code 1
