[2021-05-07 15:23:28,316] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bash_dag.print_date 2020-05-02T18:36:00+00:00 [queued]>
[2021-05-07 15:23:28,572] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: bash_dag.print_date 2020-05-02T18:36:00+00:00 [queued]>
[2021-05-07 15:23:28,572] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:23:28,573] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-05-07 15:23:28,573] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:23:28,625] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): print_date> on 2020-05-02T18:36:00+00:00
[2021-05-07 15:23:28,644] {standard_task_runner.py:52} INFO - Started process 5096 to run task
[2021-05-07 15:23:28,667] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'bash_dag', 'print_date', '2020-05-02T18:36:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag1.py', '--cfg-path', '/tmp/tmpvuhstmt8', '--error-file', '/tmp/tmp5a9eq25s']
[2021-05-07 15:23:28,674] {standard_task_runner.py:77} INFO - Job 8: Subtask print_date
[2021-05-07 15:23:30,184] {logging_mixin.py:104} INFO - Running <TaskInstance: bash_dag.print_date 2020-05-02T18:36:00+00:00 [running]> on host jaarora-WX-1.corp.adobe.com
[2021-05-07 15:23:32,159] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jacrod2901@gmail.com
AIRFLOW_CTX_DAG_OWNER=jacrod2901
AIRFLOW_CTX_DAG_ID=bash_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2020-05-02T18:36:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-02T18:36:00+00:00
[2021-05-07 15:23:32,160] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-07 15:23:32,163] {bash.py:158} INFO - Running command: date
[2021-05-07 15:23:32,224] {bash.py:169} INFO - Output:
[2021-05-07 15:23:32,350] {bash.py:173} INFO - Fri May  7 15:23:32 IST 2021
[2021-05-07 15:23:32,352] {bash.py:177} INFO - Command exited with return code 0
[2021-05-07 15:23:33,287] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=bash_dag, task_id=print_date, execution_date=20200502T183600, start_date=20210507T095328, end_date=20210507T095333
[2021-05-07 15:23:34,340] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-05-07 15:23:34,351] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5096
[2021-05-07 15:23:34,354] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-07 15:23:34,354] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-05-07 15:23:34,397] {process_utils.py:66} INFO - Process psutil.Process(pid=5096, status='terminated', exitcode=1, started='15:23:28') (5096) terminated with exit code 1
