[2021-05-07 15:38:56,330] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: python_dag.helloworld 2020-05-02T19:04:00+00:00 [queued]>
[2021-05-07 15:38:56,835] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: python_dag.helloworld 2020-05-02T19:04:00+00:00 [queued]>
[2021-05-07 15:38:56,836] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:38:56,836] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-05-07 15:38:56,837] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 15:38:56,945] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): helloworld> on 2020-05-02T19:04:00+00:00
[2021-05-07 15:38:57,017] {standard_task_runner.py:52} INFO - Started process 11489 to run task
[2021-05-07 15:38:57,098] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'python_dag', 'helloworld', '2020-05-02T19:04:00+00:00', '--job-id', '56', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_python.py', '--cfg-path', '/tmp/tmp3jw2sjz4', '--error-file', '/tmp/tmpjpdayv5i']
[2021-05-07 15:38:57,120] {standard_task_runner.py:77} INFO - Job 56: Subtask helloworld
[2021-05-07 15:38:59,602] {logging_mixin.py:104} INFO - Running <TaskInstance: python_dag.helloworld 2020-05-02T19:04:00+00:00 [running]> on host jaarora-WX-1.corp.adobe.com
[2021-05-07 15:39:01,302] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jacrod2901@gmail.com
AIRFLOW_CTX_DAG_OWNER=jacrod2901
AIRFLOW_CTX_DAG_ID=python_dag
AIRFLOW_CTX_TASK_ID=helloworld
AIRFLOW_CTX_EXECUTION_DATE=2020-05-02T19:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-05-02T19:04:00+00:00
[2021-05-07 15:39:01,309] {python.py:118} INFO - Done. Returned value was: Printing hello world!
[2021-05-07 15:39:02,576] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=python_dag, task_id=helloworld, execution_date=20200502T190400, start_date=20210507T100856, end_date=20210507T100902
[2021-05-07 15:39:03,180] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-05-07 15:39:03,198] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 11489
[2021-05-07 15:39:03,214] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-07 15:39:03,275] {process_utils.py:66} INFO - Process psutil.Process(pid=11489, status='terminated', exitcode=1, started='15:38:56') (11489) terminated with exit code 1
